In [1]:
import pandas as pd

df = pd.read_csv("Cicloparqueadero.csv")
df.head()

,X,Y,OBJECTID,ID_CICLOPARQUEDERO,CIV,CLASECICLOP,NOMBRECICLOP,SECTORCICLOP,TIPOUSUARIOCICLOP,LOCALIDAD,DIRECCIONCICLOP,HORARIOCICLOP,TIPOLOGIACICLOP,CUPOCICLOP,SELLOCICLOP,ANOCICLOP,GLOBALID
0,-74.152796,4.597898,1,1000,19015569,F,Centro comercial Paseo Villa del rio,2,1,19,DG 57C SUR 62 60,L-D 08:00 - 21:00,8,1205,2,2023,{EA7D8EEB-0574-4E7F-B9B5-68C278FD83DA}
1,-74.155887,4.580252,2,1001,19002092,F,Centro de salud candelaria,2,2,6,KR 51 59C SUR 40,L-V 07:00 - 20:00,8,48,1,2023,{10C4AEE1-AC03-4E39-B341-DFA828AC2B84}
2,-74.158162,4.570567,3,1002,19004657,F,Centro de salud Manuela Beltrán,2,2,1,KR 44D 69 SUR 16,L-V 07:00 - 20:00,8,24,1,2023,{5AAE4433-A2A0-4DD7-A748-9D382BF84E4A}
3,-74.132117,4.583610,4,1003,6000883,F,Centro de salud El Carmen,2,2,6,KR 17 25 65,L-V 07:00 - 20:00,8,24,1,2023,{E255AFCF-8194-4756-90AB-B05D03664CCC}
4,-74.152783,4.596583,5,1004,19014419,F,Makro Villa del rio,2,1,8,KR 63 57G 47,L-D 08:00 - 20:00,8,46,2,2023,{58AF8A4E-1217-4D38-BB2B-6F8637018886}

In [2]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 361 entries, 0 to 360
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   X                   361 non-null    float64
 1   Y                   361 non-null    float64
 2   OBJECTID            361 non-null    int64
 3   ID_CICLOPARQUEDERO  361 non-null    int64
 4   CIV                 361 non-null    int64
 5   CLASECICLOP         361 non-null    str
 6   NOMBRECICLOP        361 non-null    str
 7   SECTORCICLOP        361 non-null    int64
 8   TIPOUSUARIOCICLOP   361 non-null    int64
 9   LOCALIDAD           361 non-null    int64
 10  DIRECCIONCICLOP     361 non-null    str
 11  HORARIOCICLOP       361 non-null    str
 12  TIPOLOGIACICLOP     361 non-null    int64
 13  CUPOCICLOP          361 non-null    int64
 14  SELLOCICLOP         361 non-null    int64
 15  ANOCICLOP           361 non-null    int64
 16  GLOBALID            361 non-null    str
dtypes: float64(2), int64(10), str(5)
memory usage: 82.8 KB

,X,Y,OBJECTID,ID_CICLOPARQUEDERO,CIV,SECTORCICLOP,TIPOUSUARIOCICLOP,LOCALIDAD,TIPOLOGIACICLOP,CUPOCICLOP,SELLOCICLOP,ANOCICLOP
count,361.000000,361.000000,361.000000,361.00000,3.610000e+02,361.000000,361.000000,361.000000,361.000000,361.000000,361.000000,361.000000
mean,-74.085038,4.655313,181.000000,1248.98615,7.397120e+06,1.711911,1.171745,7.562327,7.387812,104.058172,1.368421,2020.229917
std,0.037633,0.049286,104.355961,403.48156,5.629255e+06,0.453501,0.377682,5.535453,1.780844,155.072239,0.483046,2.336853
min,-74.205408,4.471079,1.000000,1000.00000,0.000000e+00,1.000000,1.000000,1.000000,1.000000,8.000000,1.000000,2016.000000
25%,-74.109152,4.616059,91.000000,1090.00000,2.000709e+06,1.000000,1.000000,2.000000,8.000000,24.000000,1.000000,2018.000000
50%,-74.075029,4.658714,181.000000,1180.00000,8.007238e+06,2.000000,1.000000,8.000000,8.000000,50.000000,1.000000,2021.000000
75%,-74.055498,4.686343,271.000000,1270.00000,1.200034e+07,2.000000,1.000000,12.000000,8.000000,118.000000,2.000000,2022.000000
max,-74.023789,4.806854,361.000000,3358.00000,1.901557e+07,2.000000,2.000000,19.000000,8.000000,1205.000000,2.000000,2024.000000

In [3]:
df['CLASECICLOP'] = df['CLASECICLOP'].replace({'F': 1,'I': 2})
df['CLASECICLOP'] = df['CLASECICLOP'].astype(int)
class_df = df['CLASECICLOP'].value_counts()
print(class_df)

CLASECICLOP
1    340
2     21
Name: count, dtype: int64

In [4]:
df['SELLOCICLOP'] = df['SELLOCICLOP'].replace(2, 3)
sello_df = df['SELLOCICLOP'].value_counts()
print(sello_df)

SELLOCICLOP
1    228
3    133
Name: count, dtype: int64

In [5]:
Quality_df = df.copy()
Quality_df['Categoria'] = Quality_df['CLASECICLOP'] + Quality_df['SELLOCICLOP']

Quality_df["Categoria"] = (
    Quality_df["CLASECICLOP"] + Quality_df["SELLOCICLOP"]
).apply(lambda x: "Oro" if x == 4 else "Plata")

print(Quality_df['Categoria'])

0        Oro
1      Plata
2      Plata
3      Plata
4        Oro
       ...
356    Plata
357    Plata
358      Oro
359    Plata
360    Plata
Name: Categoria, Length: 361, dtype: str

In [6]:
#Suma de las distancias Columna X y Y
distancia_df = df.copy()
distancia_df["Distancia"] = df["X"].abs() + df["Y"].abs()
print(distancia_df['Distancia'])

0      78.750694
1      78.736139
2      78.728729
3      78.715728
4      78.749366
         ...
356    78.764880
357    78.728645
358    78.722134
359    78.670164
360    78.798224
Name: Distancia, Length: 361, dtype: float64

In [7]:
df_parqueaderos = pd.DataFrame({
    "X": df["X"],
    "Y":  df["Y"],
    'Distancia': distancia_df['Distancia'],
    'Nombre': df['NOMBRECICLOP'],
    'Direccion': df['DIRECCIONCICLOP'],
    'Horarios': df['HORARIOCICLOP'],
    'Categoria': Quality_df['Categoria'],
    })

print(df_parqueaderos)

             X         Y  Distancia                                    Nombre  \
0   -74.152796  4.597898  78.750694     Centro comercial  Paseo Villa del rio
1   -74.155887  4.580252  78.736139                Centro de salud candelaria
2   -74.158162  4.570567  78.728729           Centro de salud Manuela Beltrán
3   -74.132117  4.583610  78.715728                 Centro de salud El Carmen
4   -74.152783  4.596583  78.749366                       Makro Villa del rio
..         ...       ...        ...                                       ...
356 -74.107258  4.657622  78.764880              Edificio World Business Port
357 -74.076683  4.651962  78.728645                           City Parking 63
358 -74.049775  4.672359  78.722134                                   Amarilo
359 -74.078040  4.592124  78.670164  Ministerio de Hacienda y Crédito Público
360 -74.117267  4.680957  78.798224        City Parking World Business Center

            Direccion                               Horarios Categoria
0    DG 57C SUR 62 60                      L-D 08:00 - 21:00       Oro
1    KR 51 59C SUR 40                      L-V 07:00 - 20:00     Plata
2    KR 44D 69 SUR 16                      L-V 07:00 - 20:00     Plata
3         KR 17 25 65                      L-V 07:00 - 20:00     Plata
4        KR 63 57G 47                      L-D 08:00 - 20:00       Oro
..                ...                                    ...       ...
356      KR 69 25B 44                       L-V 7:00 - 16:30     Plata
357      AC 63  28-80                       L-S 6:00 a 22:00     Plata
358      KR 11A 89-25                       L-V 6:00 - 18:00       Oro
359        CL 6B 6-34                      L-V: 6:00 - 18:00     Plata
360       KR 86 51 66  L-V 06:00 - 20:00   S-D 06:00 - 14:00     Plata

[361 rows x 7 columns]